# Site settings
title: Prepvocab
email: prepvocab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GRE Picture Vocab & Flashcards provides an 
  effective way of learning difficult vocabulary words.
baseurl: "/blog-jekyll" # the subpath of your site, e.g. /blog/
url: "http://prepvoacb.com" # the base hostname & protocol for your site
twitter_username: hiten8080
github_username:  prepvocab

# Build settings
markdown: kramdown
